apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-config
  namespace: relibank
  labels:
    app: relibank
    component: infrastructure-config
data:
  # Database Configuration
  MSSQL_DATABASE_NAME: "RelibankDB"
  MSSQL_SERVER_NAME: "mssql-0"
  MSSQL_PORT: "1433"
  POSTGRES_DATABASE_NAME: "accountsdb"
  POSTGRES_SERVER_NAME: "accounts-db"
  POSTGRES_PORT: "5432"

  # Kafka Configuration
  KAFKA_BROKER: "kafka:29092"
  KAFKA_INTERNAL_PORT: "29092"
  KAFKA_EXTERNAL_PORT: "9092"
  KAFKA_SERVER_NAME: "kafka"

  # Zookeeper Configuration
  ZOOKEEPER_SERVER_NAME: "zookeeper"
  ZOOKEEPER_PORT: "2181"

  # Service URLs
  TRANSACTION_SERVICE_URL: "http://transaction-service:5001"
  ACCOUNTS_SERVICE_URL: "http://accounts-service:5002"
  AUTH_SERVICE_URL: "http://auth-service:5002"
  BILL_PAY_SERVICE_URL: "http://bill-pay-service:5000"
  CHATBOT_SERVICE_URL: "http://chatbot-service:5003"
  SCHEDULER_SERVICE_URL: "http://scheduler-service:5004"
  SCENARIO_RUNNER_SERVICE_URL: "http://scenario-runner-service:8000"
