apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mssql-data
  annotations:
    storageClassName: standard
  name: mssql-data
  namespace: relibank
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-data
  namespace: relibank
  labels:
    app: accounts-db
  annotations:
    storageClassName: standard
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi